require("dotenv").config();

const supportEmail = process.env.SUPPORT_EMAIL;

const diagnosticReportEmail = (userName, generatedBy = "Euphoraum-AI") => {
  return `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Your Diagnostic Report</title>
  </head>

  <body style="margin: 0; padding: 0; background-color: #F7F4ED; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;">

    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color: #F7F4ED; padding: 40px 0;">
      <tr>
        <td align="center">

          <table width="600" cellpadding="0" cellspacing="0" border="0"
            style="background-color: #ffffff; border-radius: 12px; padding: 40px; box-shadow: 0 8px 30px rgba(0,0,0,0.07);">

            <!-- Logo -->
            <tr>
              <td align="center" style="padding-bottom: 30px;">
                <img
                  src="cid:logo"
                  alt="Euphoraum-AI Logo"
                  width="110"
                  height="110"
                  style="display: block; max-width: 100%; border: 0;"
                />
              </td>
            </tr>

            <!-- Greeting -->
            <tr>
              <td style="font-size: 20px; color: #4A595A; text-align: center; padding-bottom: 16px;">
                Hello ${userName},
              </td>
            </tr>

            <!-- Main Message -->
            <tr>
              <td style="font-size: 16px; color: #333333; text-align: center; line-height: 1.6; padding-bottom: 20px;">
                Your personalized <strong>Diagnostic Report</strong> has been generated by
                <strong>${generatedBy}</strong>.
              </td>
            </tr>

            <!-- Attachment Notice -->
            <tr>
              <td style="background-color: #F7F4ED; border-radius: 8px; padding: 20px;
                         font-size: 15px; color: #333333; line-height: 1.6; text-align: center;">
                📎 <strong>Your diagnostic report is attached to this email as a PDF.</strong><br />
                Please download and review it carefully at your convenience.
              </td>
            </tr>

            <!-- Disclaimer -->
            <tr>
              <td style="font-size: 14px; color: #555555; text-align: center; line-height: 1.6; padding-top: 24px;">
                This report is generated using AI-assisted analysis and is intended for informational
                purposes only. It does not replace professional medical advice.
              </td>
            </tr>

            <!-- Support -->
            <tr>
              <td style="font-size: 14px; color: #555555; text-align: center; line-height: 1.6; padding-top: 16px;">
                If you have any questions or received this email in error, please contact us at
                <a href="mailto:${supportEmail}" style="color: #4A595A; text-decoration: none;">
                  ${supportEmail}
                </a>.
              </td>
            </tr>

            <!-- Footer -->
            <tr>
              <td style="font-size: 14px; color: #888888; text-align: center; padding-top: 40px;">
                — The Euphoraum-AI Team
              </td>
            </tr>

          </table>

        </td>
      </tr>
    </table>
  </body>
  </html>
  `;
};

module.exports = { diagnosticReportEmail };
